In [60]:
#pip install xlrd==1.2.0
import openpyxl
import xlrd
import pandas as pd
import numpy as np
from  pandas import DataFrame
from openpyxl import load_workbook
xlrd.xlsx.ensure_elementtree_imported(False, None)
xlrd.xlsx.Element_has_iter = True

In [64]:
excel_name = r'D:\my github\Internship_XCY_202209\0918\Hospital_test.xlsx'  #打开多个sheet的表格

wb = xlrd.open_workbook(excel_name) 
sheets = wb.sheet_names()  # 获取workbook中所有的表格
print(sheets)
# 下面循环遍历所有sheet
df2 = DataFrame()
for i in range(1): #每次读2个sheet
    df = pd.read_excel(excel_name, sheet_name=i)
    df2 = df2.append(df)
#所有sheet的结果合在df2中
df2

['Sheet1', '医院床位数 (2)']

,城市名称,城市规模,经济水平,地理分区（4）,地理分区（7）,老龄化率,Unnamed: 6,时间,时间2,合并1,...,Unnamed: 13,2017常住人口,2018常住人口,2019常住人口,2020常住人口,Unnamed: 18,2017每千人医院床位数,2018每千人医院床位数,2019每千人医院床位数,2020每千人医院床位数
0,安庆市,中等城市,欠发达城市,中部,华东,17.06,NaN,NaT,20120223.0,15530.0,...,NaN,464.30,469.10,470.8000,416.5284,NaN,3.344820,3.575570,3.805225,5.211409
1,蚌埠市,中等城市,欠发达城市,中部,华东,14.40,NaN,NaT,20110312.0,NaN,...,NaN,337.70,339.20,340.1700,329.6408,NaN,4.527391,5.041568,5.316753,6.514060
2,肇庆市,小城市,欠发达城市,中部,华东,13.61,NaN,NaT,NaN,NaN,...,NaN,516.90,523.70,525.0000,499.6844,NaN,2.426968,2.721023,3.132952,3.925478
3,池州市,小城市,欠发达城市,中部,华东,16.74,NaN,2016-07-08,NaN,NaN,...,NaN,144.90,147.40,148.0000,134.2764,NaN,3.580400,4.011533,4.425676,5.508786
4,肇庆市,中等城市,欠发达城市,东部,华南,11.81,NaN,2022-04-12,NaN,13426.0,...,411.54,415.17,416.98,411.3594,NaN,3.080624,3.230000,3.310000,3.450000,NaN
5,中山市,中等城市,中等发达城市,东部,华南,5.98,NaN,2022-07-08,20120223.0,15685.0,...,418.04,331.00,334.49,441.8060,NaN,3.621663,4.740000,4.790000,3.600000,NaN
6,珠海市,大城市,发达城市,东部,华南,6.64,NaN,2012-04-12,20140212.0,8849.0,...,176.54,189.11,195.75,243.9585,NaN,4.721310,4.680000,4.690000,4.130000,NaN
7,百色市,小城市,欠发达城市,西部,华南,12.39,NaN,2016-07-08,NaN,11519.0,...,364.65,366.94,367.90,357.1505,NaN,3.023721,3.140000,3.550000,3.980000,NaN
8,北海市,小城市,中等发达城市,西部,华南,11.52,NaN,2022-04-12,NaN,6056.0,...,166.33,168.00,169.06,185.3227,NaN,3.482835,3.600000,3.800000,3.780000,NaN
9,崇左市,小城市,欠发达城市,西部,华南,13.25,NaN,2022-07-08,NaN,5060.0,...,208.68,209.94,210.36,208.8692,NaN,2.432432,2.410000,2.590000,2.900000,NaN
10,防城港市,小城市,中等发达城市,西部,华南,10.03,NaN,2012-04-12,NaN,2730.0,...,94.02,95.33,95.81,104.6068,NaN,2.802595,2.860000,2.930000,3.100000,NaN
11,贵港市,小城市,欠发达城市,西部,华南,12.16,NaN,2013-07-08,NaN,11493.0,...,437.54,440.92,442.16,431.6262,NaN,2.378754,2.610000,3.080000,3.730000,NaN
12,桂林市,中等城市,欠发达城市,西部,华南,14.82,NaN,2013-04-12,NaN,16474.0,...,505.75,508.55,510.00,493.1137,NaN,3.111814,3.240000,3.510000,3.990000,NaN
13,河池市,小城市,欠发达城市,西部,华南,13.20,NaN,2013-07-08,NaN,12359.0,...,352.35,354.57,355.42,341.7945,NaN,3.314602,3.490000,5.420000,5.410000,NaN
14,贺州市,小城市,欠发达城市,西部,华南,12.50,NaN,2013-04-12,NaN,5554.0,...,205.67,207.26,208.16,200.7858,NaN,2.526863,2.680000,2.970000,3.540000,NaN
15,来宾市,小城市,欠发达城市,西部,华南,13.11,NaN,2013-07-08,NaN,6848.0,...,221.86,223.39,223.86,207.4611,NaN,2.725142,3.070000,2.860000,3.580000,NaN
16,柳州市,大城市,中等发达城市,西部,华南,12.44,NaN,2013-04-12,NaN,18545.0,...,400.00,404.17,405.94,415.7934,NaN,4.472500,4.590000,4.890000,5.150000,NaN
17,南宁市,大城市,欠发达城市,西部,华南,10.66,NaN,2013-07-08,NaN,38532.0,...,715.33,725.41,730.02,874.1584,NaN,4.979939,5.310000,5.620000,4.880000,NaN
18,钦州市,小城市,欠发达城市,西部,华南,11.46,NaN,2013-04-12,NaN,9762.0,...,328.00,330.44,331.36,330.2238,NaN,2.631707,2.950000,3.320000,3.690000,NaN

In [3]:
import openpyxl
wb = openpyxl.load_workbook(r'D:\my github\Internship_XCY_202209\0918\Hospital_test.xlsx')
sheet = wb.get_sheet_by_name('Sheet1')
print(sheet.max_row)

5

C:\Users\dell\AppData\Local\Temp/ipykernel_19696/4227321692.py:3: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).
  sheet = wb.get_sheet_by_name('Sheet1')

In [2]:
#pip install xlrd==1.2.0
import openpyxl
import xlrd
import pandas as pd
import numpy as np
from  pandas import DataFrame
from openpyxl import load_workbook
xlrd.xlsx.ensure_elementtree_imported(False, None)
xlrd.xlsx.Element_has_iter = True

In [5]:
excel_name = r'D:\my github\Internship_XCY_202209\0918\Hospital_test.xlsx'  #表格地址+表格名
wb = xlrd.open_workbook(excel_name) 
# 获取workbook中所有的表格
sheets = wb.sheet_names()
# print sheets

# 循环遍历所有sheet
alldata = DataFrame()
for i in range(len(sheets)):
    df = pd.read_excel(excel_name, sheet_name=i)
    alldata = alldata.append(df)
#查看dataframe
print(alldata)

  城市名称  城市规模    经济水平 地理分区（4） 地理分区（7）   老龄化率  Unnamed: 6                   时间  \
0  安庆市  中等城市   欠发达城市      中部      华东  17.06         NaN  2022-04-12 00:00:00
1  蚌埠市  中等城市   欠发达城市      中部      华东  14.40         NaN  2022-07-08 00:00:00
2  亳州市   小城市   欠发达城市      中部      华东  13.61         NaN  2012-04-12 00:00:00
3  池州市   小城市   欠发达城市      中部      华东  16.74         NaN  2016-07-08 00:00:00
0  北京市  超大城市    发达城市      东部      华北  13.30         NaN                  NaN
1  福州市   大城市  中等发达城市      东部      华东  11.72         NaN                  NaN
2  龙岩市   小城市  中等发达城市      东部      华东  13.33         NaN                  NaN
3  南平市   小城市  中等发达城市      东部      华东  14.79         NaN                  NaN

        合并1  2018医院床位数  ...  Unnamed: 12  2017常住人口  2018常住人口  2019常住人口  \
0   15530.0    16773.0  ...          NaN     464.3     469.1    470.80
1       NaN    17101.0  ...          NaN     337.7     339.2    340.17
2       NaN    14250.0  ...          NaN     516.9     523.7    525.00
3       NaN     5913.0  ...          NaN     144.9     147.4    148.00
0  113700.0   116279.0  ...          NaN    2170.7    2154.2   2153.88
1   30152.0    32569.0  ...          NaN     766.0     774.0    776.98
2   16615.0    17381.0  ...          NaN     264.0     264.0    264.00
3   12211.0    11965.0  ...          NaN     268.0     269.0    269.06

    2020常住人口  Unnamed: 17  2017每千人医院床位数  2018每千人医院床位数  2019每千人医院床位数  \
0   416.5284          NaN      3.344820      3.575570      3.805225
1   329.6408          NaN      4.527391      5.041568      5.316753
2   499.6844          NaN      2.426968      2.721023      3.132952
3   134.2764          NaN      3.580400      4.011533      4.425676
0  2189.3095          NaN      5.237942      5.397781      5.551563
1   829.1268          NaN      3.936292      4.207881      4.288527
2   272.3637          NaN      6.293561      6.583712      6.659848
3   268.0645          NaN      4.556343      4.447955      4.608637

   2020每千人医院床位数
0      5.211409
1      6.514060
2      3.925478
3      5.508786
0      5.449663
1      4.160401
2      6.891888
3      4.572780

[8 rows x 22 columns]

In [21]:
alldata2 = alldata[alldata['老龄化率']<14]
alldata2

,城市名称,城市规模,经济水平,地理分区（4）,地理分区（7）,老龄化率,Unnamed: 6,时间,合并1,2018医院床位数,...,Unnamed: 12,2017常住人口,2018常住人口,2019常住人口,2020常住人口,Unnamed: 17,2017每千人医院床位数,2018每千人医院床位数,2019每千人医院床位数,2020每千人医院床位数
2,亳州市,小城市,欠发达城市,中部,华东,13.61,NaN,2012-04-12 00:00:00,NaN,14250.0,...,NaN,516.9,523.7,525.00,499.6844,NaN,2.426968,2.721023,3.132952,3.925478
0,北京市,超大城市,发达城市,东部,华北,13.30,NaN,NaN,113700.0,116279.0,...,NaN,2170.7,2154.2,2153.88,2189.3095,NaN,5.237942,5.397781,5.551563,5.449663
1,福州市,大城市,中等发达城市,东部,华东,11.72,NaN,NaN,30152.0,32569.0,...,NaN,766.0,774.0,776.98,829.1268,NaN,3.936292,4.207881,4.288527,4.160401
2,龙岩市,小城市,中等发达城市,东部,华东,13.33,NaN,NaN,16615.0,17381.0,...,NaN,264.0,264.0,264.00,272.3637,NaN,6.293561,6.583712,6.659848,6.891888

In [59]:
'''
# coding=utf-8
import xlrd
import sys
import pandas as pd
import imp
imp.reload(sys)
#reload(sys)
#sys.setdefaultencoding('utf-8')
import traceback
from datetime import datetime
from xlrd import xldate_as_tuple
 
class excelHandle:
    def decode(self, filename, sheetname):
        return filename, sheetname
 
    def read_excel(self, filename, sheetname):
        filename, sheetname = self.decode(filename, sheetname)
        rbook = xlrd.open_workbook(filename)
        sheet = rbook.sheet_by_name(sheetname)
        rows = sheet.nrows
        cols = sheet.ncols
        all_content = []
        for i in range(rows):
            row_content = []
            for j in range(cols):
                ctype = sheet.cell(i, j).ctype  # 表格的数据类型
                cell = sheet.cell_value(i, j)
                if ctype == 2 and cell % 1 == 0:  # 如果是整形
                    cell = int(cell)
                elif ctype == 3:
                    # 转成datetime对象
                    date = datetime(*xldate_as_tuple(cell, 0))
                    cell = date.strftime('%Y/%m/%d')
                elif ctype == 4:
                    cell = True if cell == 1 else False
                row_content.append(cell)
            all_content.append(row_content)
            print( '[' + ','.join("'" + str(element) + "'" for element in row_content) + ']')
        return all_content
 
if __name__ == '__main__':
    eh = excelHandle()
    filename = r'D:\my github\Internship_XCY_202209\0918\Hospital_test.xlsx'
    sheetname = 'Sheet1'
    A = pd.DataFrame(eh.read_excel(filename, sheetname))
    A.to_excel("a1.xlsx") #输出结果
'''

'\n# coding=utf-8\nimport xlrd\nimport sys\nimport pandas as pd\nimport imp\nimp.reload(sys)\n#reload(sys)\n#sys.setdefaultencoding(\'utf-8\')\nimport traceback\nfrom datetime import datetime\nfrom xlrd import xldate_as_tuple\n \nclass excelHandle:\n    def decode(self, filename, sheetname):\n        return filename, sheetname\n \n    def read_excel(self, filename, sheetname):\n        filename, sheetname = self.decode(filename, sheetname)\n        rbook = xlrd.open_workbook(filename)\n        sheet = rbook.sheet_by_name(sheetname)\n        rows = sheet.nrows\n        cols = sheet.ncols\n        all_content = []\n        for i in range(rows):\n            row_content = []\n            for j in range(cols):\n                ctype = sheet.cell(i, j).ctype  # 表格的数据类型\n                cell = sheet.cell_value(i, j)\n                if ctype == 2 and cell % 1 == 0:  # 如果是整形\n                    cell = int(cell)\n                elif ctype == 3:\n                    # 转成datetime对象\n                    date = datetime(*xldate_as_tuple(cell, 0))\n                    cell = date.strftime(\'%Y/%m/%d\')\n                elif ctype == 4:\n                    cell = True if cell == 1 else False\n                row_content.append(cell)\n            all_content.append(row_content)\n            print( \'[\' + \',\'.join("\'" + str(element) + "\'" for element in row_content) + \']\')\n        return all_content\n \nif __name__ == \'__main__\':\n    eh = excelHandle()\n    filename = r\'D:\\my github\\Internship_XCY_202209\x00918\\Hospital_test.xlsx\'\n    sheetname = \'Sheet1\'\n    A = pd.DataFrame(eh.read_excel(filename, sheetname))\n    A.to_excel("a1.xlsx") #输出结果\n'

In [16]:
df1= pd.read_excel(r'D:\my github\Internship_XCY_202209\0918\Hospital_test.xlsx',sheet_name='Sheet1',usecols=[8])
df1

           时间2
0   20120223.0
1   20110312.0
2          NaN
3          NaN
4          NaN
5   20120223.0
6   20140212.0
7          NaN
8          NaN
9          NaN
10         NaN
11         NaN
12         NaN
13         NaN
14         NaN
15         NaN
16         NaN
17         NaN
18         NaN

In [18]:
for i in df1.items():
    i = str(tuple(i))
    print(i)
#    i = datetime.strptime(i, '%Y%m%d')
    ? = i

('时间2', 0     20120223.0
1     20110312.0
2            NaN
3            NaN
4            NaN
5     20120223.0
6     20140212.0
7            NaN
8            NaN
9            NaN
10           NaN
11           NaN
12           NaN
13           NaN
14           NaN
15           NaN
16           NaN
17           NaN
18           NaN
Name: 时间2, dtype: float64)

In [8]:
from datetime import datetime
y = datetime.strptime(df1['时间2'], '%Y%m%d')

TypeError: strptime() argument 1 must be str, not Series

In [ ]:
df.groupby(df["城市规模"])[str(2017+m)+'每千人医院床位数'].var()

In [ ]:
group = df.groupby(['gender', 'level'])
# 先按照'grade'列的值来分组。每组内，再按'level'列来分组。也返回一个groupby对象
for key, value in group:
    print(key)
    print(value)
    print("")
('man', 'a')

In [105]:
df2 = pd.DataFrame(df1.groupby(df1["地理分区（4）"])['经济水平'].count())
df2

         经济水平
地理分区（4）
东部          3
中部          4
西部         12

In [101]:
df2 = pd.DataFrame(df1.groupby(df1["经济水平"])['城市规模'].count())
df2

        城市规模
经济水平
中等发达城市     4
发达城市       1
欠发达城市     14

In [98]:
df2 = pd.DataFrame(df1.groupby(df1["经济水平"])['城市规模'].count())
df2

         经济水平
地理分区（4）
东部          4

In [4]:
result = df1.merge(df0,how='left',on=['城市名称'])
result

,城市名称,城市规模,经济水平,地理分区（4）,地理分区（7）,老龄化率,Unnamed: 6,时间,合并1_x,2018医院床位数,...,2018常住人口,2019常住人口,2020常住人口,Unnamed: 17,2017每千人医院床位数,2018每千人医院床位数,2019每千人医院床位数,2020每千人医院床位数,合并1_y,合并2_y
0,安庆市,中等城市,欠发达城市,中部,华东,17.06,NaN,2022-04-12,15530.0,16773.000000,...,469.10,470.80,416.5284,NaN,3.344820,3.575570,3.805225,5.211409,NaN,NaN
1,蚌埠市,中等城市,欠发达城市,中部,华东,14.40,NaN,2022-07-08,NaN,17101.000000,...,339.20,340.17,329.6408,NaN,4.527391,5.041568,5.316753,6.514060,15289.0,NaN
2,蚌埠市,中等城市,欠发达城市,中部,华东,14.40,NaN,2022-07-08,NaN,17101.000000,...,339.20,340.17,329.6408,NaN,4.527391,5.041568,5.316753,6.514060,15289.0,NaN
3,亳州市,小城市,欠发达城市,中部,华东,13.61,NaN,2012-04-12,NaN,14250.000000,...,523.70,525.00,499.6844,NaN,2.426968,2.721023,3.132952,3.925478,12545.0,16448.0
4,池州市,小城市,欠发达城市,中部,华东,16.74,NaN,2016-07-08,NaN,5913.000000,...,147.40,148.00,134.2764,NaN,3.580400,4.011533,4.425676,5.508786,5188.0,6550.0
5,滁州市,小城市,中等发达城市,中部,华东,15.97,NaN,2012-04-12,NaN,14419.000000,...,411.40,413.04,398.7054,NaN,3.366290,3.504861,3.979518,4.954034,13721.0,16437.0
6,阜阳市,中等城市,欠发达城市,中部,华东,13.79,NaN,2016-07-08,NaN,32749.000000,...,820.70,823.31,820.0264,NaN,3.513283,3.990374,4.243602,4.763017,28433.0,34938.0
7,合肥市,大城市,中等发达城市,中部,华东,11.99,NaN,2012-04-12,NaN,48042.000000,...,808.70,813.77,936.9881,NaN,5.361833,5.940645,6.425034,6.325694,42707.0,52285.0
8,淮北市,中等城市,欠发达城市,中部,华东,13.44,NaN,2016-07-08,NaN,9252.000000,...,225.40,226.21,197.0265,NaN,4.147666,4.104703,4.600150,5.650001,9241.0,10406.0
9,淮南市,大城市,欠发达城市,中部,华东,16.37,NaN,2012-04-12,13645.0,14470.000000,...,349.00,348.95,303.3528,NaN,3.913106,4.146132,4.296031,5.129012,NaN,14991.0
10,黄山市,小城市,欠发达城市,中部,华东,18.11,NaN,2016-07-08,6368.0,6735.000000,...,140.70,141.39,133.0565,NaN,4.601156,4.786780,4.929627,5.871942,NaN,6970.0
11,六安市,小城市,欠发达城市,中部,华东,16.86,NaN,NaT,12302.0,12874.000000,...,483.70,485.47,439.3699,NaN,2.562917,2.661567,2.758770,3.891482,NaN,13393.0
12,马鞍山市,中等城市,中等发达城市,中部,华东,17.53,NaN,NaT,7610.0,7922.000000,...,233.70,234.90,215.9930,NaN,3.305821,3.389816,3.660707,5.390915,NaN,8599.0
13,宿州市,中等城市,欠发达城市,中部,华东,14.83,NaN,NaT,15415.0,16323.000000,...,568.14,569.12,532.4476,NaN,2.724943,2.873059,3.103915,4.312537,NaN,17665.0
14,铜陵市,小城市,欠发达城市,中部,华东,17.46,NaN,NaT,6678.0,7815.000000,...,162.90,163.47,131.1726,NaN,4.152985,4.797422,4.747660,6.207089,NaN,7761.0
15,芜湖市,大城市,中等发达城市,中部,华东,16.11,NaN,NaT,17741.0,18133.000000,...,374.80,376.27,364.4420,NaN,4.800054,4.838047,4.946182,6.368640,NaN,18611.0
16,宣城市,小城市,欠发达城市,中部,华东,18.04,NaN,NaT,10043.0,12811.148346,...,264.80,265.39,250.0063,NaN,3.842005,4.838047,4.424055,5.030273,NaN,11741.0
17,北京市,超大城市,发达城市,东部,华北,13.30,NaN,NaT,113700.0,116279.000000,...,2154.20,2153.88,2189.3095,NaN,5.237942,5.397781,5.551563,5.449663,NaN,119574.0
18,福州市,大城市,中等发达城市,东部,华东,11.72,NaN,NaT,30152.0,32569.000000,...,774.00,776.98,829.1268,NaN,3.936292,4.207881,4.288527,4.160401,NaN,33321.0
19,龙岩市,小城市,中等发达城市,东部,华东,13.33,NaN,NaT,16615.0,17381.000000,...,264.00,264.00,272.3637,NaN,6.293561,6.583712,6.659848,6.891888,NaN,NaN
20,南平市,小城市,中等发达城市,东部,华东,14.79,NaN,NaT,12211.0,11965.000000,...,269.00,269.06,268.0645,NaN,4.556343,4.447955,4.608637,4.572780,NaN,NaN