In [1]:
import pandas as pd
import numpy as np

In [2]:
df1=pd.read_excel(r'D:\my github\Internship_XCY_202209\0918\Hospital_test.xlsx')
df1

,城市名称,城市规模,经济水平,地理分区（4）,地理分区（7）,老龄化率,Unnamed: 6,合并1,2018医院床位数,合并2,...,Unnamed: 11,2017常住人口,2018常住人口,2019常住人口,2020常住人口,Unnamed: 16,2017每千人医院床位数,2018每千人医院床位数,2019每千人医院床位数,2020每千人医院床位数
0,安庆市,中等城市,欠发达城市,中部,华东,17.06,NaN,15530.0,16773.0,17915.0,...,NaN,464.3,469.10,470.80,416.5284,NaN,3.344820,3.575570,3.805225,5.211409
1,蚌埠市,中等城市,欠发达城市,中部,华东,14.40,NaN,NaN,17101.0,18086.0,...,NaN,337.7,339.20,340.17,329.6408,NaN,4.527391,5.041568,5.316753,6.514060
2,亳州市,小城市,欠发达城市,中部,华东,13.61,NaN,NaN,14250.0,NaN,...,NaN,516.9,523.70,525.00,499.6844,NaN,2.426968,2.721023,3.132952,3.925478
3,池州市,小城市,欠发达城市,中部,华东,16.74,NaN,NaN,5913.0,NaN,...,NaN,144.9,147.40,148.00,134.2764,NaN,3.580400,4.011533,4.425676,5.508786
4,滁州市,小城市,中等发达城市,中部,华东,15.97,NaN,NaN,14419.0,NaN,...,NaN,407.6,411.40,413.04,398.7054,NaN,3.366290,3.504861,3.979518,4.954034
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
291,绍兴市,中等城市,中等发达城市,东部,华东,16.21,NaN,21242.0,21651.0,22001.0,...,NaN,501.0,503.50,504.62,527.0977,NaN,4.239920,4.300099,4.359914,4.571449
292,台州市,大城市,中等发达城市,东部,华东,13.80,NaN,24955.0,26879.0,27762.0,...,NaN,611.8,613.90,614.45,662.2888,NaN,4.078947,4.378400,4.518187,4.270946
293,温州市,大城市,中等发达城市,东部,华东,11.71,NaN,36327.0,37414.0,38313.0,...,NaN,921.5,925.00,927.48,957.2903,NaN,3.942160,4.044757,4.130871,4.040363
294,舟山市,中等城市,中等发达城市,东部,华东,17.09,NaN,5056.0,5698.0,5632.0,...,NaN,116.8,117.30,117.48,115.7817,NaN,4.328767,4.857630,4.794007,5.210668
295,重庆市,超大城市,中等发达城市,西部,西南,16.30,NaN,150500.0,162147.0,171576.0,...,NaN,3144.0,3101.79,3113.10,3212.4300,NaN,4.786896,5.227530,5.511419,5.446251

In [3]:
df2=pd.read_excel(r'D:\my github\Internship_XCY_202209\0918\Hospital_test_2.xlsx')
df2

    城市名称      合并1      合并2
0    安庆市      NaN      NaN
1    蚌埠市  15289.0      NaN
2    亳州市  12545.0  16448.0
3    池州市   5188.0   6550.0
4    滁州市  13721.0  16437.0
..   ...      ...      ...
291  绍兴市      NaN      NaN
292  台州市      NaN      NaN
293  温州市      NaN      NaN
294  舟山市      NaN      NaN
295  重庆市      NaN      NaN

[296 rows x 3 columns]

In [4]:
help(pd.merge)

Help on function merge in module pandas.core.reshape.merge:

merge(left: 'DataFrame | Series', right: 'DataFrame | Series', how: 'str' = 'inner', on: 'IndexLabel | None' = None, left_on: 'IndexLabel | None' = None, right_on: 'IndexLabel | None' = None, left_index: 'bool' = False, right_index: 'bool' = False, sort: 'bool' = False, suffixes: 'Suffixes' = ('_x', '_y'), copy: 'bool' = True, indicator: 'bool' = False, validate: 'str | None' = None) -> 'DataFrame'
    Merge DataFrame or named Series objects with a database-style join.

    A named Series object is treated as a DataFrame with a single named column.

    The join is done on columns or indexes. If joining columns on
    columns, the DataFrame indexes *will be ignored*. Otherwise if joining indexes
    on indexes or indexes on a column or columns, the index will be passed on.
    When performing a cross merge, no column specifications to merge on are
    allowed.

    Parameters
    ----------
    left : DataFrame
    right : DataFrame or named Series
        Object to merge with.
    how : {'left', 'right', 'outer', 'inner', 'cross'}, default 'inner'
        Type of merge to be performed.

        * left: use only keys from left frame, similar to a SQL left outer join;
          preserve key order.
        * right: use only keys from right frame, similar to a SQL right outer join;
          preserve key order.
        * outer: use union of keys from both frames, similar to a SQL full outer
          join; sort keys lexicographically.
        * inner: use intersection of keys from both frames, similar to a SQL inner
          join; preserve the order of the left keys.
        * cross: creates the cartesian product from both frames, preserves the order
          of the left keys.

          .. versionadded:: 1.2.0

    on : label or list
        Column or index level names to join on. These must be found in both
        DataFrames. If `on` is None and not merging on indexes then this defaults
        to the intersection of the columns in both DataFrames.
    left_on : label or list, or array-like
        Column or index level names to join on in the left DataFrame. Can also
        be an array or list of arrays of the length of the left DataFrame.
        These arrays are treated as if they are columns.
    right_on : label or list, or array-like
        Column or index level names to join on in the right DataFrame. Can also
        be an array or list of arrays of the length of the right DataFrame.
        These arrays are treated as if they are columns.
    left_index : bool, default False
        Use the index from the left DataFrame as the join key(s). If it is a
        MultiIndex, the number of keys in the other DataFrame (either the index
        or a number of columns) must match the number of levels.
    right_index : bool, default False
        Use the index from the right DataFrame as the join key. Same caveats as
        left_index.
    sort : bool, default False
        Sort the join keys lexicographically in the result DataFrame. If False,
        the order of the join keys depends on the join type (how keyword).
    suffixes : list-like, default is ("_x", "_y")
        A length-2 sequence where each element is optionally a string
        indicating the suffix to add to overlapping column names in
        `left` and `right` respectively. Pass a value of `None` instead
        of a string to indicate that the column name from `left` or
        `right` should be left as-is, with no suffix. At least one of the
        values must not be None.
    copy : bool, default True
        If False, avoid copy if possible.
    indicator : bool or str, default False
        If True, adds a column to the output DataFrame called "_merge" with
        information on the source of each row. The column can be given a different
        name by providing a string argument. The column will have a Categorical
        type with the value of "left_only" for observations whose merge key only
        appears in the left DataFrame, "right_only" for observations
        whose merge key only appears in the right DataFrame, and "both"
        if the observation's merge key is found in both DataFrames.

    validate : str, optional
        If specified, checks if merge is of specified type.

        * "one_to_one" or "1:1": check if merge keys are unique in both
          left and right datasets.
        * "one_to_many" or "1:m": check if merge keys are unique in left
          dataset.
        * "many_to_one" or "m:1": check if merge keys are unique in right
          dataset.
        * "many_to_many" or "m:m": allowed, but does not result in checks.

    Returns
    -------
    DataFrame
        A DataFrame of the two merged objects.

    See Also
    --------
    merge_ordered : Merge with optional filling/interpolation.
    merge_asof : Merge on nearest keys.
    DataFrame.join : Similar method using indices.

    Notes
    -----
    Support for specifying index levels as the `on`, `left_on`, and
    `right_on` parameters was added in version 0.23.0
    Support for merging named Series objects was added in version 0.24.0

    Examples
    --------
    >>> df1 = pd.DataFrame({'lkey': ['foo', 'bar', 'baz', 'foo'],
    ...                     'value': [1, 2, 3, 5]})
    >>> df2 = pd.DataFrame({'rkey': ['foo', 'bar', 'baz', 'foo'],
    ...                     'value': [5, 6, 7, 8]})
    >>> df1
        lkey value
    0   foo      1
    1   bar      2
    2   baz      3
    3   foo      5
    >>> df2
        rkey value
    0   foo      5
    1   bar      6
    2   baz      7
    3   foo      8

    Merge df1 and df2 on the lkey and rkey columns. The value columns have
    the default suffixes, _x and _y, appended.

    >>> df1.merge(df2, left_on='lkey', right_on='rkey')
      lkey  value_x rkey  value_y
    0  foo        1  foo        5
    1  foo        1  foo        8
    2  foo        5  foo        5
    3  foo        5  foo        8
    4  bar        2  bar        6
    5  baz        3  baz        7

    Merge DataFrames df1 and df2 with specified left and right suffixes
    appended to any overlapping columns.

    >>> df1.merge(df2, left_on='lkey', right_on='rkey',
    ...           suffixes=('_left', '_right'))
      lkey  value_left rkey  value_right
    0  foo           1  foo            5
    1  foo           1  foo            8
    2  foo           5  foo            5
    3  foo           5  foo            8
    4  bar           2  bar            6
    5  baz           3  baz            7

    Merge DataFrames df1 and df2, but raise an exception if the DataFrames have
    any overlapping columns.

    >>> df1.merge(df2, left_on='lkey', right_on='rkey', suffixes=(False, False))
    Traceback (most recent call last):
    ...
    ValueError: columns overlap but no suffix specified:
        Index(['value'], dtype='object')

    >>> df1 = pd.DataFrame({'a': ['foo', 'bar'], 'b': [1, 2]})
    >>> df2 = pd.DataFrame({'a': ['foo', 'baz'], 'c': [3, 4]})
    >>> df1
          a  b
    0   foo  1
    1   bar  2
    >>> df2
          a  c
    0   foo  3
    1   baz  4

    >>> df1.merge(df2, how='inner', on='a')
          a  b  c
    0   foo  1  3

    >>> df1.merge(df2, how='left', on='a')
          a  b  c
    0   foo  1  3.0
    1   bar  2  NaN

    >>> df1 = pd.DataFrame({'left': ['foo', 'bar']})
    >>> df2 = pd.DataFrame({'right': [7, 8]})
    >>> df1
        left
    0   foo
    1   bar
    >>> df2
        right
    0   7
    1   8

    >>> df1.merge(df2, how='cross')
       left  right
    0   foo      7
    1   foo      8
    2   bar      7
    3   bar      8

In [5]:
result = df1.merge(df2,how='outer',on=['城市名称'])
result

,城市名称,城市规模,经济水平,地理分区（4）,地理分区（7）,老龄化率,Unnamed: 6,合并1_x,2018医院床位数,合并2_x,...,2018常住人口,2019常住人口,2020常住人口,Unnamed: 16,2017每千人医院床位数,2018每千人医院床位数,2019每千人医院床位数,2020每千人医院床位数,合并1_y,合并2_y
0,安庆市,中等城市,欠发达城市,中部,华东,17.06,NaN,15530.0,16773.0,17915.0,...,469.10,470.80,416.5284,NaN,3.344820,3.575570,3.805225,5.211409,NaN,NaN
1,蚌埠市,中等城市,欠发达城市,中部,华东,14.40,NaN,NaN,17101.0,18086.0,...,339.20,340.17,329.6408,NaN,4.527391,5.041568,5.316753,6.514060,15289.0,NaN
2,亳州市,小城市,欠发达城市,中部,华东,13.61,NaN,NaN,14250.0,NaN,...,523.70,525.00,499.6844,NaN,2.426968,2.721023,3.132952,3.925478,12545.0,16448.0
3,池州市,小城市,欠发达城市,中部,华东,16.74,NaN,NaN,5913.0,NaN,...,147.40,148.00,134.2764,NaN,3.580400,4.011533,4.425676,5.508786,5188.0,6550.0
4,滁州市,小城市,中等发达城市,中部,华东,15.97,NaN,NaN,14419.0,NaN,...,411.40,413.04,398.7054,NaN,3.366290,3.504861,3.979518,4.954034,13721.0,16437.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
291,绍兴市,中等城市,中等发达城市,东部,华东,16.21,NaN,21242.0,21651.0,22001.0,...,503.50,504.62,527.0977,NaN,4.239920,4.300099,4.359914,4.571449,NaN,NaN
292,台州市,大城市,中等发达城市,东部,华东,13.80,NaN,24955.0,26879.0,27762.0,...,613.90,614.45,662.2888,NaN,4.078947,4.378400,4.518187,4.270946,NaN,NaN
293,温州市,大城市,中等发达城市,东部,华东,11.71,NaN,36327.0,37414.0,38313.0,...,925.00,927.48,957.2903,NaN,3.942160,4.044757,4.130871,4.040363,NaN,NaN
294,舟山市,中等城市,中等发达城市,东部,华东,17.09,NaN,5056.0,5698.0,5632.0,...,117.30,117.48,115.7817,NaN,4.328767,4.857630,4.794007,5.210668,NaN,NaN
295,重庆市,超大城市,中等发达城市,西部,西南,16.30,NaN,150500.0,162147.0,171576.0,...,3101.79,3113.10,3212.4300,NaN,4.786896,5.227530,5.511419,5.446251,NaN,NaN

In [12]:
result.loc[result['合并1_x'].isna(),'合并1_x']=result[result['合并1_x'].isna()]['合并1_y']
result

,城市名称,城市规模,经济水平,地理分区（4）,地理分区（7）,老龄化率,Unnamed: 6,合并1_x,2018医院床位数,合并2_x,...,2018常住人口,2019常住人口,2020常住人口,Unnamed: 16,2017每千人医院床位数,2018每千人医院床位数,2019每千人医院床位数,2020每千人医院床位数,合并1_y,合并2_y
0,安庆市,中等城市,欠发达城市,中部,华东,17.06,NaN,15530.0,16773.0,17915.0,...,469.10,470.80,416.5284,NaN,3.344820,3.575570,3.805225,5.211409,NaN,NaN
1,蚌埠市,中等城市,欠发达城市,中部,华东,14.40,NaN,15289.0,17101.0,18086.0,...,339.20,340.17,329.6408,NaN,4.527391,5.041568,5.316753,6.514060,15289.0,NaN
2,亳州市,小城市,欠发达城市,中部,华东,13.61,NaN,12545.0,14250.0,NaN,...,523.70,525.00,499.6844,NaN,2.426968,2.721023,3.132952,3.925478,12545.0,16448.0
3,池州市,小城市,欠发达城市,中部,华东,16.74,NaN,5188.0,5913.0,NaN,...,147.40,148.00,134.2764,NaN,3.580400,4.011533,4.425676,5.508786,5188.0,6550.0
4,滁州市,小城市,中等发达城市,中部,华东,15.97,NaN,13721.0,14419.0,NaN,...,411.40,413.04,398.7054,NaN,3.366290,3.504861,3.979518,4.954034,13721.0,16437.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
291,绍兴市,中等城市,中等发达城市,东部,华东,16.21,NaN,21242.0,21651.0,22001.0,...,503.50,504.62,527.0977,NaN,4.239920,4.300099,4.359914,4.571449,NaN,NaN
292,台州市,大城市,中等发达城市,东部,华东,13.80,NaN,24955.0,26879.0,27762.0,...,613.90,614.45,662.2888,NaN,4.078947,4.378400,4.518187,4.270946,NaN,NaN
293,温州市,大城市,中等发达城市,东部,华东,11.71,NaN,36327.0,37414.0,38313.0,...,925.00,927.48,957.2903,NaN,3.942160,4.044757,4.130871,4.040363,NaN,NaN
294,舟山市,中等城市,中等发达城市,东部,华东,17.09,NaN,5056.0,5698.0,5632.0,...,117.30,117.48,115.7817,NaN,4.328767,4.857630,4.794007,5.210668,NaN,NaN
295,重庆市,超大城市,中等发达城市,西部,西南,16.30,NaN,150500.0,162147.0,171576.0,...,3101.79,3113.10,3212.4300,NaN,4.786896,5.227530,5.511419,5.446251,NaN,NaN